export const SHOP_MAIN_PAGE_MOCK_DATA = [
  {
    title: '전체',
    key: 'all',
    categorySVG: 'ALL',
    brand: [
      '전체',
      '할리스',
      '컴포즈',
      '폴 바셋',
      '엔제리너스',
      '탐앤탐스',
      '세븐일레븐',
      'CU',
      '이마트',
      '미니스토어',
      'GS25',
      '바이더웨이',
      '버거킹',
      '맥도날드',
      '롯데리아',
      '시장통',
      '쉑쉑버거',
      '피자헛',
      '피자앤',
      '판다피자',
      '올리비아',
      '쇼파',
      '티비피자',
      '교촌치킨',
      'BBQ',
      '호랑이',
      '비둘기치킨',
      '거위치킨',
      '티베트치킨',
    ],
    products: [
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },

      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },

      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },

      {
        key: '세븐일레븐 상품권 5000원',
        title: '세븐일레븐 상품권 5000원',
        category: '편의점',
        brand: '세븐일레븐',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'CU 상품권 5000원',
        title: 'CU 상품권 5000원',
        category: '편의점',
        brand: 'CU',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 상품권 5000원',
        title: '이마트 상품권 5000원',
        category: '편의점',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '미니스토어 5000원 상품권',
        title: '미니스토어 5000원 상품권',
        category: '편의점',
        brand: '미니스토어',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'GS 25 5000원 상품권',
        title: 'GS 25 5000원 상품권',
        category: '편의점',
        brand: 'GS25',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '바이더웨이 5000원 상품권',
        title: '바이더웨이 5000원 상품권',
        category: '편의점',
        brand: '바이더웨이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '세븐일레븐 상품권 5000원',
        title: '세븐일레븐 상품권 5000원',
        category: '편의점',
        brand: '세븐일레븐',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'CU 상품권 5000원',
        title: 'CU 상품권 5000원',
        category: '편의점',
        brand: 'CU',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 상품권 5000원',
        title: '이마트 상품권 5000원',
        category: '편의점',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '미니스토어 5000원 상품권',
        title: '미니스토어 5000원 상품권',
        category: '편의점',
        brand: '미니스토어',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'GS 25 5000원 상품권',
        title: 'GS 25 5000원 상품권',
        category: '편의점',
        brand: 'GS25',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '바이더웨이 5000원 상품권',
        title: '바이더웨이 5000원 상품권',
        category: '편의점',
        brand: '바이더웨이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '세븐일레븐 상품권 5000원',
        title: '세븐일레븐 상품권 5000원',
        category: '편의점',
        brand: '세븐일레븐',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'CU 상품권 5000원',
        title: 'CU 상품권 5000원',
        category: '편의점',
        brand: 'CU',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 상품권 5000원',
        title: '이마트 상품권 5000원',
        category: '편의점',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '미니스토어 5000원 상품권',
        title: '미니스토어 5000원 상품권',
        category: '편의점',
        brand: '미니스토어',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'GS 25 5000원 상품권',
        title: 'GS 25 5000원 상품권',
        category: '편의점',
        brand: 'GS25',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '바이더웨이 5000원 상품권',
        title: '바이더웨이 5000원 상품권',
        category: '편의점',
        brand: '바이더웨이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },

      {
        key: '버거킹 햄버거',
        title: '버거킹 햄버거',
        category: '햄버거',
        brand: '버거킹',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '맥도날드 더블 불고기버거',
        title: '맥도날드 더블 불고기버거',
        category: '햄버거',
        brand: '맥도날드',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '롯데리아 한우버거',
        title: '롯데리아 한우버거',
        category: '햄버거',
        brand: '롯데리아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 브랜드 버거',
        title: '이마트 브랜드 버거',
        category: '햄버거',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '시장통 햄버거',
        title: '시장통 햄버거',
        category: '햄버거',
        brand: '시장통',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쉑쉑 치즈 버거',
        title: '쉑쉑 치즈 버거',
        category: '햄버거',
        brand: '쉑쉑버거',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '버거킹 햄버거',
        title: '버거킹 햄버거',
        category: '햄버거',
        brand: '버거킹',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '맥도날드 더블 불고기버거',
        title: '맥도날드 더블 불고기버거',
        category: '햄버거',
        brand: '맥도날드',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '롯데리아 한우버거',
        title: '롯데리아 한우버거',
        category: '햄버거',
        brand: '롯데리아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 브랜드 버거',
        title: '이마트 브랜드 버거',
        category: '햄버거',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '시장통 햄버거',
        title: '시장통 햄버거',
        category: '햄버거',
        brand: '시장통',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쉑쉑 치즈 버거',
        title: '쉑쉑 치즈 버거',
        category: '햄버거',
        brand: '쉑쉑버거',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '버거킹 햄버거',
        title: '버거킹 햄버거',
        category: '햄버거',
        brand: '버거킹',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '맥도날드 더블 불고기버거',
        title: '맥도날드 더블 불고기버거',
        category: '햄버거',
        brand: '맥도날드',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '롯데리아 한우버거',
        title: '롯데리아 한우버거',
        category: '햄버거',
        brand: '롯데리아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 브랜드 버거',
        title: '이마트 브랜드 버거',
        category: '햄버거',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '시장통 햄버거',
        title: '시장통 햄버거',
        category: '햄버거',
        brand: '시장통',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쉑쉑 치즈 버거',
        title: '쉑쉑 치즈 버거',
        category: '햄버거',
        brand: '쉑쉑버거',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },

      {
        key: '피자헛 불고기 피자',
        title: '피자헛 불고기 피자',
        category: '피자',
        brand: '피자헛',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자앤 고구마피자',
        title: '피자앤 고구마피자',
        category: '피자',
        brand: '피자앤',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '판다 새우킹 피자',
        title: '판다 새우킹 피자',
        category: '피자',
        brand: '판다피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '올리비아 핫 쉬림프 피자',
        title: '올리비아 핫 쉬림프 피자',
        category: '피자',
        brand: '올리비아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쇼파에서 누워 먹는 피자',
        title: '쇼파에서 누워 먹는 피자',
        category: '피자',
        brand: '쇼파',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티비에서 광고 많이 하는 피자',
        title: '티비에서 광고 많이 하는 피자',
        category: '피자',
        brand: '티비피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자헛 불고기 피자',
        title: '피자헛 불고기 피자',
        category: '피자',
        brand: '피자헛',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자앤 고구마피자',
        title: '피자앤 고구마피자',
        category: '피자',
        brand: '피자앤',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '판다 새우킹 피자',
        title: '판다 새우킹 피자',
        category: '피자',
        brand: '판다피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '올리비아 핫 쉬림프 피자',
        title: '올리비아 핫 쉬림프 피자',
        category: '피자',
        brand: '올리비아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쇼파에서 누워 먹는 피자',
        title: '쇼파에서 누워 먹는 피자',
        category: '피자',
        brand: '쇼파',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티비에서 광고 많이 하는 피자',
        title: '티비에서 광고 많이 하는 피자',
        category: '피자',
        brand: '티비피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자헛 불고기 피자',
        title: '피자헛 불고기 피자',
        category: '피자',
        brand: '피자헛',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자앤 고구마피자',
        title: '피자앤 고구마피자',
        category: '피자',
        brand: '피자앤',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '판다 새우킹 피자',
        title: '판다 새우킹 피자',
        category: '피자',
        brand: '판다피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '올리비아 핫 쉬림프 피자',
        title: '올리비아 핫 쉬림프 피자',
        category: '피자',
        brand: '올리비아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쇼파에서 누워 먹는 피자',
        title: '쇼파에서 누워 먹는 피자',
        category: '피자',
        brand: '쇼파',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티비에서 광고 많이 하는 피자',
        title: '티비에서 광고 많이 하는 피자',
        category: '피자',
        brand: '티비피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },

      {
        key: '교촌 레드콤보',
        title: '교촌 레드콤보',
        category: '치킨',
        brand: '교촌치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'BBQ 황금올리브 치킨',
        title: 'BBQ 황금올리브 치킨',
        category: '치킨',
        brand: 'BBQ',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '호랑이 힘이 솟는다 치킨',
        title: '호랑이 힘이 솟는다 치킨',
        category: '치킨',
        brand: '호랑이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '비둘기 날아라 날개 치킨',
        title: '비둘기 날아라 날개 치킨',
        category: '치킨',
        brand: '비둘기치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '거위 푸아그라 치킨',
        title: '거위 푸아그라 치킨',
        category: '치킨',
        brand: '거위치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티베트 초염도 치킨',
        title: '티베트 초염도 치킨',
        category: '치킨',
        brand: '티베트치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '교촌 레드콤보',
        title: '교촌 레드콤보',
        category: '치킨',
        brand: '교촌치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'BBQ 황금올리브 치킨',
        title: 'BBQ 황금올리브 치킨',
        category: '치킨',
        brand: 'BBQ',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '호랑이 힘이 솟는다 치킨',
        title: '호랑이 힘이 솟는다 치킨',
        category: '치킨',
        brand: '호랑이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '비둘기 날아라 날개 치킨',
        title: '비둘기 날아라 날개 치킨',
        category: '치킨',
        brand: '비둘기치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '거위 푸아그라 치킨',
        title: '거위 푸아그라 치킨',
        category: '치킨',
        brand: '거위치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티베트 초염도 치킨',
        title: '티베트 초염도 치킨',
        category: '치킨',
        brand: '티베트치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '교촌 레드콤보',
        title: '교촌 레드콤보',
        category: '치킨',
        brand: '교촌치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'BBQ 황금올리브 치킨',
        title: 'BBQ 황금올리브 치킨',
        category: '치킨',
        brand: 'BBQ',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '호랑이 힘이 솟는다 치킨',
        title: '호랑이 힘이 솟는다 치킨',
        category: '치킨',
        brand: '호랑이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '비둘기 날아라 날개 치킨',
        title: '비둘기 날아라 날개 치킨',
        category: '치킨',
        brand: '비둘기치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '거위 푸아그라 치킨',
        title: '거위 푸아그라 치킨',
        category: '치킨',
        brand: '거위치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티베트 초염도 치킨',
        title: '티베트 초염도 치킨',
        category: '치킨',
        brand: '티베트치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
    ],
  },
  {
    title: '유틸리티',
    key: 'util',
    categorySVG: 'UTIL',
    brand: ['전체', '할리스', '컴포즈', '폴 바셋', '엔제리너스', '탐앤탐스'],
    products: [
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
    ],
  },
  {
    title: '카페',
    key: 'cafe',
    categorySVG: 'CAFE',
    brand: ['전체', '할리스', '컴포즈', '폴 바셋', '엔제리너스', '탐앤탐스'],
    products: [
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피치 딸기 크러쉬',
        title: '피치 딸기 크러쉬',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '자몽 에이드 ',
        title: '자몽 에이드 ',
        category: '카페',
        brand: '할리스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '녹차 프라페',
        title: '녹차 프라페',
        category: '카페',
        brand: '컴포즈',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피스타치오 프라푸치노',
        title: '피스타치오 프라푸치노',
        category: '카페',
        brand: '폴 바셋',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '페퍼민트 TEA',
        title: '페퍼민트 TEA',
        category: '카페',
        brand: '엔제리너스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '아이스 아메리카노',
        title: '아이스 아메리카노',
        category: '카페',
        brand: '탐앤탐스',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
    ],
  },
  {
    title: '편의점',
    key: 'convenience-store',
    categorySVG: 'CONVENIENCE',
    brand: ['전체', '세븐일레븐', 'CU', '이마트', '미니스토어', 'GS25', '바이더웨이'],
    products: [
      {
        key: '세븐일레븐 상품권 5000원',
        title: '세븐일레븐 상품권 5000원',
        category: '편의점',
        brand: '세븐일레븐',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'CU 상품권 5000원',
        title: 'CU 상품권 5000원',
        category: '편의점',
        brand: 'CU',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 상품권 5000원',
        title: '이마트 상품권 5000원',
        category: '편의점',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '미니스토어 5000원 상품권',
        title: '미니스토어 5000원 상품권',
        category: '편의점',
        brand: '미니스토어',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'GS 25 5000원 상품권',
        title: 'GS 25 5000원 상품권',
        category: '편의점',
        brand: 'GS25',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '바이더웨이 5000원 상품권',
        title: '바이더웨이 5000원 상품권',
        category: '편의점',
        brand: '바이더웨이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '세븐일레븐 상품권 5000원',
        title: '세븐일레븐 상품권 5000원',
        category: '편의점',
        brand: '세븐일레븐',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'CU 상품권 5000원',
        title: 'CU 상품권 5000원',
        category: '편의점',
        brand: 'CU',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 상품권 5000원',
        title: '이마트 상품권 5000원',
        category: '편의점',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '미니스토어 5000원 상품권',
        title: '미니스토어 5000원 상품권',
        category: '편의점',
        brand: '미니스토어',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'GS 25 5000원 상품권',
        title: 'GS 25 5000원 상품권',
        category: '편의점',
        brand: 'GS25',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '바이더웨이 5000원 상품권',
        title: '바이더웨이 5000원 상품권',
        category: '편의점',
        brand: '바이더웨이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '세븐일레븐 상품권 5000원',
        title: '세븐일레븐 상품권 5000원',
        category: '편의점',
        brand: '세븐일레븐',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'CU 상품권 5000원',
        title: 'CU 상품권 5000원',
        category: '편의점',
        brand: 'CU',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 상품권 5000원',
        title: '이마트 상품권 5000원',
        category: '편의점',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '미니스토어 5000원 상품권',
        title: '미니스토어 5000원 상품권',
        category: '편의점',
        brand: '미니스토어',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'GS 25 5000원 상품권',
        title: 'GS 25 5000원 상품권',
        category: '편의점',
        brand: 'GS25',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '바이더웨이 5000원 상품권',
        title: '바이더웨이 5000원 상품권',
        category: '편의점',
        brand: '바이더웨이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
    ],
  },
  {
    title: '버거',
    key: 'burger',
    categorySVG: 'BURGER',
    brand: ['전체', '버거킹', '맥도날드', '롯데리아', '시장통', '쉑쉑버거'],
    products: [
      {
        key: '버거킹 햄버거',
        title: '버거킹 햄버거',
        category: '햄버거',
        brand: '버거킹',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '맥도날드 더블 불고기버거',
        title: '맥도날드 더블 불고기버거',
        category: '햄버거',
        brand: '맥도날드',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '롯데리아 한우버거',
        title: '롯데리아 한우버거',
        category: '햄버거',
        brand: '롯데리아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 브랜드 버거',
        title: '이마트 브랜드 버거',
        category: '햄버거',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '시장통 햄버거',
        title: '시장통 햄버거',
        category: '햄버거',
        brand: '시장통',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쉑쉑 치즈 버거',
        title: '쉑쉑 치즈 버거',
        category: '햄버거',
        brand: '쉑쉑버거',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '버거킹 햄버거',
        title: '버거킹 햄버거',
        category: '햄버거',
        brand: '버거킹',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '맥도날드 더블 불고기버거',
        title: '맥도날드 더블 불고기버거',
        category: '햄버거',
        brand: '맥도날드',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '롯데리아 한우버거',
        title: '롯데리아 한우버거',
        category: '햄버거',
        brand: '롯데리아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 브랜드 버거',
        title: '이마트 브랜드 버거',
        category: '햄버거',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '시장통 햄버거',
        title: '시장통 햄버거',
        category: '햄버거',
        brand: '시장통',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쉑쉑 치즈 버거',
        title: '쉑쉑 치즈 버거',
        category: '햄버거',
        brand: '쉑쉑버거',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '버거킹 햄버거',
        title: '버거킹 햄버거',
        category: '햄버거',
        brand: '버거킹',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '맥도날드 더블 불고기버거',
        title: '맥도날드 더블 불고기버거',
        category: '햄버거',
        brand: '맥도날드',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '롯데리아 한우버거',
        title: '롯데리아 한우버거',
        category: '햄버거',
        brand: '롯데리아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '이마트 브랜드 버거',
        title: '이마트 브랜드 버거',
        category: '햄버거',
        brand: '이마트',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '시장통 햄버거',
        title: '시장통 햄버거',
        category: '햄버거',
        brand: '시장통',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쉑쉑 치즈 버거',
        title: '쉑쉑 치즈 버거',
        category: '햄버거',
        brand: '쉑쉑버거',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
    ],
  },
  {
    title: '피자',
    key: 'pizza',
    categorySVG: 'PIZZA',
    brand: ['전체', '피자헛', '피자앤', '판다피자', '올리비아', '쇼파', '티비피자'],
    products: [
      {
        key: '피자헛 불고기 피자',
        title: '피자헛 불고기 피자',
        category: '피자',
        brand: '피자헛',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자앤 고구마피자',
        title: '피자앤 고구마피자',
        category: '피자',
        brand: '피자앤',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '판다 새우킹 피자',
        title: '판다 새우킹 피자',
        category: '피자',
        brand: '판다피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '올리비아 핫 쉬림프 피자',
        title: '올리비아 핫 쉬림프 피자',
        category: '피자',
        brand: '올리비아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쇼파에서 누워 먹는 피자',
        title: '쇼파에서 누워 먹는 피자',
        category: '피자',
        brand: '쇼파',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티비에서 광고 많이 하는 피자',
        title: '티비에서 광고 많이 하는 피자',
        category: '피자',
        brand: '티비피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자헛 불고기 피자',
        title: '피자헛 불고기 피자',
        category: '피자',
        brand: '피자헛',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자앤 고구마피자',
        title: '피자앤 고구마피자',
        category: '피자',
        brand: '피자앤',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '판다 새우킹 피자',
        title: '판다 새우킹 피자',
        category: '피자',
        brand: '판다피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '올리비아 핫 쉬림프 피자',
        title: '올리비아 핫 쉬림프 피자',
        category: '피자',
        brand: '올리비아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쇼파에서 누워 먹는 피자',
        title: '쇼파에서 누워 먹는 피자',
        category: '피자',
        brand: '쇼파',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티비에서 광고 많이 하는 피자',
        title: '티비에서 광고 많이 하는 피자',
        category: '피자',
        brand: '티비피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자헛 불고기 피자',
        title: '피자헛 불고기 피자',
        category: '피자',
        brand: '피자헛',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '피자앤 고구마피자',
        title: '피자앤 고구마피자',
        category: '피자',
        brand: '피자앤',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '판다 새우킹 피자',
        title: '판다 새우킹 피자',
        category: '피자',
        brand: '판다피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '올리비아 핫 쉬림프 피자',
        title: '올리비아 핫 쉬림프 피자',
        category: '피자',
        brand: '올리비아',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '쇼파에서 누워 먹는 피자',
        title: '쇼파에서 누워 먹는 피자',
        category: '피자',
        brand: '쇼파',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티비에서 광고 많이 하는 피자',
        title: '티비에서 광고 많이 하는 피자',
        category: '피자',
        brand: '티비피자',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
    ],
  },
  {
    title: '치킨',
    key: 'chicken',
    categorySVG: 'CHICKEN',
    brand: ['전체', '교촌치킨', 'BBQ', '호랑이', '비둘기', '거위치킨', '티베트치킨'],
    products: [
      {
        key: '교촌 레드콤보',
        title: '교촌 레드콤보',
        category: '치킨',
        brand: '교촌치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'BBQ 황금올리브 치킨',
        title: 'BBQ 황금올리브 치킨',
        category: '치킨',
        brand: 'BBQ',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '호랑이 힘이 솟는다 치킨',
        title: '호랑이 힘이 솟는다 치킨',
        category: '치킨',
        brand: '호랑이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '비둘기 날아라 날개 치킨',
        title: '비둘기 날아라 날개 치킨',
        category: '치킨',
        brand: '비둘기치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '거위 푸아그라 치킨',
        title: '거위 푸아그라 치킨',
        category: '치킨',
        brand: '거위치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티베트 초염도 치킨',
        title: '티베트 초염도 치킨',
        category: '치킨',
        brand: '티베트치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '교촌 레드콤보',
        title: '교촌 레드콤보',
        category: '치킨',
        brand: '교촌치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'BBQ 황금올리브 치킨',
        title: 'BBQ 황금올리브 치킨',
        category: '치킨',
        brand: 'BBQ',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '호랑이 힘이 솟는다 치킨',
        title: '호랑이 힘이 솟는다 치킨',
        category: '치킨',
        brand: '호랑이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '비둘기 날아라 날개 치킨',
        title: '비둘기 날아라 날개 치킨',
        category: '치킨',
        brand: '비둘기치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '거위 푸아그라 치킨',
        title: '거위 푸아그라 치킨',
        category: '치킨',
        brand: '거위치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티베트 초염도 치킨',
        title: '티베트 초염도 치킨',
        category: '치킨',
        brand: '티베트치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '교촌 레드콤보',
        title: '교촌 레드콤보',
        category: '치킨',
        brand: '교촌치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: 'BBQ 황금올리브 치킨',
        title: 'BBQ 황금올리브 치킨',
        category: '치킨',
        brand: 'BBQ',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '호랑이 힘이 솟는다 치킨',
        title: '호랑이 힘이 솟는다 치킨',
        category: '치킨',
        brand: '호랑이',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '비둘기 날아라 날개 치킨',
        title: '비둘기 날아라 날개 치킨',
        category: '치킨',
        brand: '비둘기치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '거위 푸아그라 치킨',
        title: '거위 푸아그라 치킨',
        category: '치킨',
        brand: '거위치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
      {
        key: '티베트 초염도 치킨',
        title: '티베트 초염도 치킨',
        category: '치킨',
        brand: '티베트치킨',
        sale: 30,
        price: 4500,
        image: '/images/shop-main-sample-stabucks.jpg',
      },
    ],
  },
]

export const SHOP_DROP_DOWN_MOCK_DATA = [
  {
    text: '판매인기순',
    key: 'popular',
  },
  {
    text: '낮은가격순',
    key: 'down-price',
  },
  {
    text: '높은가격순',
    key: 'high-price',
  },
]

export const recommendation = [
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '피치 딸기 크러쉬',
    title: '피치 딸기 크러쉬',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
  {
    key: '자몽 에이드 ',
    title: '자몽 에이드 ',
    category: '카페',
    brand: '할리스',
    sale: 30,
    price: 4500,
    image: '/images/shop-main-sample-stabucks.jpg',
  },
]
