import type { Metadata } from 'next';
import './globals.css';
import FooterNavigation from '@/components/FooterNavigation/FooterNavigation';
import HeaderComponent from '@/components/HeaderComponent/HeaderComponent';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&family=Alfa+Slab+One&family=Noto+Sans+KR:wght@100..900&family=Gothic+A1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <HeaderComponent />
        {children}
        <FooterNavigation />
      </body>
    </html>
  );
}
